#!/bin/sh

set -e

if [ -d ndk-pkg-formula-repository-official-core ] ; then
    git -C ndk-pkg-formula-repository-official-core pull
else
    git clone --depth=1 https://github.com/leleliu008/ndk-pkg-formula-repository-official-core
fi

cd ndk-pkg-formula-repository-official-core/formula

ls *.yml | sed 's|\.yml$||' | sort | uniq > a

sed -n '/^dep-pkg:/p' *.yml | cut -c10- | tr ' ' '\n' | sort | uniq > b

SED="sed -e s|^-||"

for item in d8 v8 skia pdfium webrtc tensorflow-lite libvips librsvg libint dash
do
    SED="$SED -e /^$item$/d"
done

echo "SED=$SED"

PKGS="$(diff -U 0 a b | sed '/^--/d' | grep '^-' | $SED)"

PKGS_COUNT="$(printf "$PKGS" | wc -l)"
PKGS_COUNT="$(($PKGS_COUNT + 1))"

echo "PKGS_COUNT=$PKGS_COUNT"

cd -

cat > .github/workflows/publish.yml <<EOF
name: publish

on:
  workflow_dispatch

jobs:
EOF

unset ITEMS
unset NEEDS

I=0
J=0
K=0

for item in $PKGS
do
    if [ -z "$ITEMS" ] ; then
        ITEMS="$item"
    else
        ITEMS="$ITEMS, $item"
    fi

    K=$(($K + 1))

    J=$(($J + 1))

    echo "J=$J"
    echo "K=$K"

    if [ "$J" = 256 ] || [ "$K" = "$PKGS_COUNT" ] ; then
        J=0
        I=$(($I + 1))

        cat >> .github/workflows/publish.yml <<EOF

  build$I:
    strategy:
      fail-fast: false
      matrix:
        pkg: [$ITEMS]

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: /usr/bin/ndk-pkg about
      - run: /usr/bin/ndk-pkg setup
      - run: /usr/bin/ndk-pkg update

      - name: build
        run: |
          case \${{ matrix.pkg }} in
            cmake)
              /usr/bin/ndk-pkg install android-34-arm64-v8a/\${{ matrix.pkg }} --static
              ;;
            *)
              /usr/bin/ndk-pkg install android-29-arm64-v8a/\${{ matrix.pkg }}
              ;;
          esac

      - name: pack
        run: |
          set -ex
          for item in \$(/usr/bin/ndk-pkg ls-installed)
          do
              /usr/bin/ndk-pkg pack "\$item" -o .

              PACKAGE_SUMMARY="\$(/usr/bin/ndk-pkg info-installed "\$item" summary)"
              PACKAGE_WEB_URL="\$(/usr/bin/ndk-pkg info-installed "\$item" web-url)"
              PACKAGE_VERSION="\$(/usr/bin/ndk-pkg info-installed "\$item" version)"

              PACKAGE_NAME="\${item#*/}"

              PACKAGE_FILENAME="\$(ls \${PACKAGE_NAME%@*}-\$PACKAGE_VERSION-*.tar.xz)"

              PACKAGE_BIN_SHA="\$(sha256sum "\$PACKAGE_FILENAME" | cut -d ' ' -f1)"

              PACKAGE_BIN_URL="https://github.com/\${{ github.repository }}/releases/download/@TAGNAME@/\$PACKAGE_FILENAME"

              cat > "\$PACKAGE_NAME.yml" <<EOF
          summary: \$PACKAGE_SUMMARY
          webpage: \$PACKAGE_WEB_URL
          version: \$PACKAGE_VERSION
          bin-url: \$PACKAGE_BIN_URL
          bin-sha: \$PACKAGE_BIN_SHA
          EOF
          done

      - uses: actions/upload-artifact@v4
        with:
          name: \${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml
EOF

        unset ITEMS

        if [ -z "$NEEDS" ] ; then
            NEEDS="build$I"
        else
            NEEDS="$NEEDS, build$I"
        fi
    fi
done

cat >> .github/workflows/publish.yml <<EOF

  publish:
    needs: [$NEEDS]

EOF

cat >> .github/workflows/publish.yml < foot
