name: publish

on:
  workflow_dispatch

jobs:

  build1:
    strategy:
      fail-fast: false
      matrix:
        pkg: [ARM_NEON_2_x86_SSE, aalib, acl, act, actionlint, adig, ag, age, alass, algernon, antibody, apkeep, aptly, archiver, args, aria2, arping, awk, axel, azcopy, b3sum, base16, base64, bash, basis_universal, bat, bc, bcrypt, bgrep, binaryen, bind, binocle, bison, bk, blockhash, boringssl, boxes, brook, broot, brotli, bsdtar, bullet, busybox, byacc, bzip2, caddy, cargo-c, catch2, ccache, cereal, cflow, cgal, cheat, check, chezmoi, chinese-calendar, chisel, choose, cilium-cli, cjson, cli11, clog, cmake, cmark, cmatrix, cmocka, coreutils, cotp, cpio, cpprestsdk, cpptoml, cppunit, cpuid, cpuinfo, croc, crosstool-ng, crowbook, ctop, cue, curl, curlie, cxxopts, d2, darkhttpd, dasel, dav1d, delta, diffutils, dns2tcp, dnslookup, dnsmap, dnsx, dog, doggo, dos2unix, dot_static, double-conversion, doxygen, dua, duf, dufs, duktape, dust, easyutils, ed, elvish, epsilon, erdtree, esbuild, ethereum, exa, exhale, exiv2, eza, faac, faad2, fcp, fd, fdk-aac, fdroidcl, fff, figlet, file, findent, findutils, fish, flac, flatc, flex, flock, fontconfig, fortune, fselect, fsmon, fswatch, fzf, fzy, g, garble, gat, gawk, gbt, gdk-pixbuf, gdu, geographiclib, germanium, getopt, gettext, gettext-tools, gf, gh, ghr, gif, gindent, git, git-cliff, git-lfs, gitui, gitwatch, glab, glib-tools, glog, glow, glslang, gm4, gmake, gn, gnu-barcode, gnu-which, gnupg, go-md2man, go-tools, godu, gogs, golang, gomobile, google-benchmark, gopls, goreleaser, gosh, gotop, gotty, gox, gperf, gperftools, gping, gpsim, gputils, graphicsmagick, graphviz, grep, grex, gron, grpc, grpc-plugins, gsed, gtar, gtime, gzip, halibut, helix, helm, hexdump, hexyl, htop, htslib, httpx, hugo, hunspell, hurl, hwloc, hydroxide, hyperfine, id3lib, ideviceinstaller, invoice, ipinfo, isl, iw, ixwebsocket, jfrog-cli, jj, jpegoptim, jq, json-glib, jump, kcp, kcptun, keybase, ko, krb5, lame, lazygit, lcms2, lcov, ldns, less, lf, libaec, libaio, libao, libargp, libasprintf, libass, libasync++, libatomic_ops, libb2, libb64, libbcrypt, libbluray, libcaca, libcap, libcbor, libcddb, libcdio, libcerf]

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: /usr/bin/ndk-pkg about
      - run: /usr/bin/ndk-pkg setup
      - run: /usr/bin/ndk-pkg update

      - name: build
        run: |
          case ${{ matrix.pkg }} in
            cmake)
              /usr/bin/ndk-pkg install android-34-arm64-v8a/${{ matrix.pkg }} --static
              ;;
            *)
              /usr/bin/ndk-pkg install android-29-arm64-v8a/${{ matrix.pkg }}
              ;;
          esac

      - name: pack
        run: |
          set -ex
          for item in $(/usr/bin/ndk-pkg ls-installed)
          do
              /usr/bin/ndk-pkg pack "$item" -o .

              PACKAGE_SUMMARY="$(/usr/bin/ndk-pkg info-installed "$item" summary)"
              PACKAGE_WEB_URL="$(/usr/bin/ndk-pkg info-installed "$item" web-url)"
              PACKAGE_VERSION="$(/usr/bin/ndk-pkg info-installed "$item" version)"

              PACKAGE_NAME="${item#*/}"

              PACKAGE_FILENAME="$(ls ${PACKAGE_NAME%@*}-$PACKAGE_VERSION-*.tar.xz)"

              PACKAGE_BIN_SHA="$(sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

              PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

              cat > "$PACKAGE_NAME.yml" <<EOF
          summary: $PACKAGE_SUMMARY
          webpage: $PACKAGE_WEB_URL
          version: $PACKAGE_VERSION
          bin-url: $PACKAGE_BIN_URL
          bin-sha: $PACKAGE_BIN_SHA
          EOF
          done

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build2:
    strategy:
      fail-fast: false
      matrix:
        pkg: [libcfitsio, libcgif, libcroco, libduktape, libexhale, libexiv2, libflatbuffers, libgeotiff, libgetdomainname, libglm, libgraphene, libhexdump, libilbc, libimagequant, libintl-lite, libirecovery, libisoburn, libjpeg, libldns, libleveldb, liblinear, liblmdb, liblua, libmaxminddb, libmblen, libmd, libmesalink, libmetalink, libmhash, libmill, libmimalloc, libminiupnpc, libminiz, libmpc, libmpir, libnetpbm, libnng, libobstack, libopenh264, libphonenumber, libphysfs, libpipeline, libpng++, libpsl, libpugixml, libqalculate, libqpdf, libqrencode, libquiche, libraqm, libraw, libre, libre2c, libressl, librtmp, libsamplerate, libsigsegv, libsimdjson, libsmi, libsndfile, libspatialite, libspectre, libspiro, libspng, libsrt, libsrtp, libsvg, libsvm, libtextstyle, libthai, libtinyalsa, libtinyxml2, libtorrent-rasterbar, libtwolame, libuninameslist, libunwind, libupnp, libusrsctp, libwavpack, libwebm, libwmf, libwv2, libxcrypt, libyuv, libz3, libzim, libzlog, libzmq, lief, lighttpd, livego, llhttp, lmdb, lnd, lodepng, log4cplus, lolcat, lrzip, lsd, lsof, luajit, luau, lunzip, lychee, lynx, lz4, lzip, lzop, magic_enum, mawk, mcfly, md4c, mdbook, mediainfo, minisign, mm-wiki, mold, mosh, mozjpeg, mpdecimal, mpg123, mruby@3.0.0, mruby@3.2.0, msgpack-c, naabu, nano, nanomsg, nap, nasm, navi, ncdu, ndk-pkg-core, neofetch, netcat, nethogs, netpbm, nghttp2, nginx, ngtcp2, ninja, nlohmann-json, nnn, nsh, ntbtls, nuclei, numactl, nushell, oat++, obfs4proxy, oboe, okta-aws-cli, opa, openal-soft, opencolorio, opencv, openlibm, openmpi, openssl, openssl-fips, p7zip, packcc, patch, patchelf, pbzip2, pcapplusplus, pcre2, pegof, pget, pigz, pjsip, pkg-config, pkgconf, plog, plzip, png, pngcheck, pngquant, pngsplit, poco, ppkg, procs, progress, proj, proot2, protobuf, psimd, pup, putty, pv, pybind11, q, qpdf, qrencode, quickjs, ragel, rancher, rang, rapidjson, rav1e, rclone, re2c, restic, resvg, ripgrep, ripgrep-all, rlwrap, rover, rsass, rsync, rtmpdump, rtorrent, ruff, rust-analyzer, ruy, sassc, scc, scdoc, sd, shaderc, shc, shell2http, shellharden, shiori, silicon, sjpeg, skcms, sl, soundtouch, spdlog, speex, sqlite3, starship, stwolame, stylua, subfinder, supervisord, suricata, svn-lite, swig, syncthing, sysinfo, szip, taglib, tarlz, tbox, tcl, tcpdump, tdu, tealdeer, tectonic, tengo, tiff, tig, tinyalsa, tlrc, tmux]

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: /usr/bin/ndk-pkg about
      - run: /usr/bin/ndk-pkg setup
      - run: /usr/bin/ndk-pkg update

      - name: build
        run: |
          case ${{ matrix.pkg }} in
            cmake)
              /usr/bin/ndk-pkg install android-34-arm64-v8a/${{ matrix.pkg }} --static
              ;;
            *)
              /usr/bin/ndk-pkg install android-29-arm64-v8a/${{ matrix.pkg }}
              ;;
          esac

      - name: pack
        run: |
          set -ex
          for item in $(/usr/bin/ndk-pkg ls-installed)
          do
              /usr/bin/ndk-pkg pack "$item" -o .

              PACKAGE_SUMMARY="$(/usr/bin/ndk-pkg info-installed "$item" summary)"
              PACKAGE_WEB_URL="$(/usr/bin/ndk-pkg info-installed "$item" web-url)"
              PACKAGE_VERSION="$(/usr/bin/ndk-pkg info-installed "$item" version)"

              PACKAGE_NAME="${item#*/}"

              PACKAGE_FILENAME="$(ls ${PACKAGE_NAME%@*}-$PACKAGE_VERSION-*.tar.xz)"

              PACKAGE_BIN_SHA="$(sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

              PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

              cat > "$PACKAGE_NAME.yml" <<EOF
          summary: $PACKAGE_SUMMARY
          webpage: $PACKAGE_WEB_URL
          version: $PACKAGE_VERSION
          bin-url: $PACKAGE_BIN_URL
          bin-sha: $PACKAGE_BIN_SHA
          EOF
          done

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build3:
    strategy:
      fail-fast: false
      matrix:
        pkg: [tokei, toml++, toml11, totp-cli, tree, trietool, ttyd, ttygif, ttyrec, tut, tweego, typos, uctags, unbound, unrar, uppm, uppm@0.15.2, uppm@0.15.3, uppm@0.15.4, usbmuxd, utf8.h, utfcpp, uthash, util-linux, valijson, vegeta, vim, virustotal-cli, vulkan-headers, wabt, wasm3, wasmtime, watchexec, wavpack, webhook, webp, websocat, wget, whois, wolfssl, x264, x265, xh, xmake, xmlstarlet, xmlutils, xmlwf, xnnpack, xorriso, xpup, xsltproc, xxd, xxhash, xz, yaml-cpp, yasm, youtubedr, yq, yyjson, zip, zlib, zlib-ng, zola, zopfli, zoxide, zsh, zstd, zsync]

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: /usr/bin/ndk-pkg about
      - run: /usr/bin/ndk-pkg setup
      - run: /usr/bin/ndk-pkg update

      - name: build
        run: |
          case ${{ matrix.pkg }} in
            cmake)
              /usr/bin/ndk-pkg install android-34-arm64-v8a/${{ matrix.pkg }} --static
              ;;
            *)
              /usr/bin/ndk-pkg install android-29-arm64-v8a/${{ matrix.pkg }}
              ;;
          esac

      - name: pack
        run: |
          set -ex
          for item in $(/usr/bin/ndk-pkg ls-installed)
          do
              /usr/bin/ndk-pkg pack "$item" -o .

              PACKAGE_SUMMARY="$(/usr/bin/ndk-pkg info-installed "$item" summary)"
              PACKAGE_WEB_URL="$(/usr/bin/ndk-pkg info-installed "$item" web-url)"
              PACKAGE_VERSION="$(/usr/bin/ndk-pkg info-installed "$item" version)"

              PACKAGE_NAME="${item#*/}"

              PACKAGE_FILENAME="$(ls ${PACKAGE_NAME%@*}-$PACKAGE_VERSION-*.tar.xz)"

              PACKAGE_BIN_SHA="$(sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

              PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

              cat > "$PACKAGE_NAME.yml" <<EOF
          summary: $PACKAGE_SUMMARY
          webpage: $PACKAGE_WEB_URL
          version: $PACKAGE_VERSION
          bin-url: $PACKAGE_BIN_URL
          bin-sha: $PACKAGE_BIN_SHA
          EOF
          done

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  publish:
    needs: [build1, build2, build3]

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls

      - run: |
          set -ex

          TAGNAME="$(date +%Y.%m.%d)"

          sed -i "s|@TAGNAME@|$TAGNAME|" *.yml

          mv *.yml formula/

          DIRNAME="uppm-formula-repository-android-29-aarch64-$TAGNAME"

          install -d "$DIRNAME"

          cp -r formula "$DIRNAME/"

          tar cvJf "$DIRNAME.tar.xz" "$DIRNAME"

          sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [ndk-pkg](https://github.com/leleliu008/ndk-pkg).

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          gh release create "$TAGNAME" sha256sums.txt --title "$TAGNAME" --notes-file notes.md

          for f in *.tar.xz
          do
            sleep 1s
            gh release upload "$TAGNAME" "$f"
          done

          git config --global user.name  "leleliu008"
          git config --global user.email "leleliu008@gmail.com"

          git pull

          git add formula
          git commit -m "release new version $TAGNAME"
          git push origin master
